# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  ['-p', 'require.resolve("react-native/scripts/react_native_pods.rb", { paths: [process.argv[1]] })', __dir__]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Always use static frameworks for React Native
use_frameworks! :linkage => :static

target 'socialApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # 🔥 Firebase (via CocoaPods ONLY — no manual frameworks)
  # pod 'Firebase/Core'
  # pod 'Firebase/Auth'
  # pod 'Firebase/Firestore'
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Messaging'
  # pod 'Firebase/Crashlytics'
  # pod 'Firebase/Database'
  # pod 'Firebase/Storage'
  # pod 'Firebase/InAppMessaging'
    # pod 'react-native-config', :path => '../node_modules/react-native-config'
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix for Xcode + static frameworks warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      end
    end
  end
end
